---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  labels:
    app: prometheus
spec:
  storageClassName: prom-hdd-5g
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
