apiVersion: v1
kind: Secret
metadata:
  name: rmsecret
type: Opaque
stringData:
  user: testuser
  password: testpassword
  REDMINE_SECRET_KEY_BASE: supersecretkey
#data:    # It doesn't work. Wrong coding-decoding base64. So do use stringData option!!!
#  user: dGVzdHVzZXIK
#  password: dGVzdHBhc3N3b3JkCg==
#  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXkK
